# Generated by Django 4.2.7 on 2023-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='id',
            field=models.CharField(default='exit', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
