# Generated by Django 4.2.7 on 2023-11-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_edge_id_alter_edge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='weigth',
        ),
    ]
