# Generated by Django 4.2.7 on 2023-11-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_edge_weigth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Vertex',
        ),
    ]
