# Generated by Django 4.2.7 on 2023-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='isCovered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='vertex',
            name='vertexType',
            field=models.CharField(default=False, max_length=9, null=True),
        ),
    ]
