# Generated by Django 4.2.7 on 2023-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_edge_iscovered_vertex_vertextype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertex',
            name='vertexType',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
