# Generated by Django 4.2.7 on 2023-12-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_edge_iscrowded'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertex',
            name='isAcessible',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='vertex',
            name='observation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
