# Generated by Django 4.2.7 on 2023-12-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_vertex_isacessible_vertex_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertex',
            name='observation',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
