# Generated by Django 4.2.7 on 2023-12-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_vertex_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='height',
            field=models.FloatField(),
        ),
    ]
